# MAKEFILE for LaTeX

### Typografie a publikovani ###

# Meno: Robert Durovic
# Login: xdurov01
# Datum: 04/2017
# Projekt: proj5

### Prezentace ###

filename=proj5

all:
	pdflatex $(filename).tex

clean:
	rm -f $(filename).aux $(filename).log $(filename).dvi $(filename).ps $(filename).out
